#!/bin/sh
#Copy the initramfs
mkdir -p kernel/usr/initramfs
rm -rf kernel/usr/initramfs/*
cp -R ../initramfs_N7000_ics/* kernel/usr/initramfs
chmod -R g-w kernel/usr/initramfs/*
rm $(find kernel/usr/initramfs -name EMPTY_DIRECTORY -print)
rm -rf $(find kernel/usr/initramfs -name .git -print)
#Enable FIPS mode
export USE_SEC_FIPS_MODE=true
export LOCALVERSION="-HomuraNote-ICS"
export KBUILD_BUILD_USER="Homura"
export KBUILD_BUILD_HOST="Akemi"
export KBUILD_BUILD_VERSION="HomuHomu2"
BUILD_DEFCONFIG=dd_galaxynote_defconfig

# make start
echo "=====> cleaning"
make clean
cp -f ./arch/arm/configs/$BUILD_DEFCONFIG ./.config
  make -C $PWD oldconfig || exit -1

echo "=====> build start"
if [ -e make.log ]; then
  mv make.log make_old.log
fi
nice -n 10 make -j12 2>&1 | tee make.log

echo "Copying Modules"
cp -a $(find . -name *.ko -print |grep -v initramfs) kernel/usr/initramfs/lib/modules/
echo "Modules Copied"
sleep 5
touch kernel/usr/initramfs
echo "Rebuilding kernel with new initramfs"
make -j12
# adb shell reboot download
# sleep 5
# heimdall flash --kernel arch/arm/boot/zImage
